name: darlin
description: A comprehensive Dart package that provides Kotlin-like utilities and extensions for enhanced null safety, string manipulation, list operations, boolean logic, and scope functions.
version: 1.0.2
homepage: https://github.com/sidcasmm
repository: https://github.com/sidcasmm/darlin
issue_tracker: https://github.com/sidcasmm/darlin/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.2


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# The following section is specific to Flutter packages.
flutter:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

# The following section adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.
# cupertino_icons: ^1.0.2
